<table>
    <thead>
    <tr>
        <th id="config-name" colspan="3">
            {{{CONFIG-NAME}}} - {{{NUMBER-SERVICE}}}
        </th>
    </tr>
    </thead>

    <thead>
    <tr>
        <th class="cel-key">KEY</th>
        <th class="cel-value">VALUE</th>
        <th class="cel-options">OPTIONS</th>
    </tr>
    </thead>

    <tbody id="tbody-configs">
    <tr>
        <td>KEY</td>
        <td>VALUE</td>
        <td>OPTIONS</td>
    </tr>
    <tr>
        <td>KEY</td>
        <td>VALUE</td>
        <td>OPTIONS</td>
    </tr>
    <tr>
        <td>KEY</td>
        <td>VALUE</td>
        <td>OPTIONS</td>
    </tr>
    <tr>
        <td>KEY</td>
        <td>VALUE</td>
        <td>OPTIONS</td>
    </tr>
    <tr>
        <td>KEY</td>
        <td>VALUE</td>
        <td>OPTIONS</td>
    </tr>
    <tr>
        <td>KEY</td>
        <td>VALUE</td>
        <td>OPTIONS</td>
    </tr>
    <tr>
        <td>KEY</td>
        <td>VALUE</td>
        <td>OPTIONS</td>
    </tr>
    <tr>
        <td>KEY</td>
        <td>VALUE</td>
        <td>OPTIONS</td>
    </tr>
    <tr>
        <td>KEY</td>
        <td>VALUE</td>
        <td>OPTIONS</td>
    </tr>
    <tr>
        <td>KEY</td>
        <td>VALUE</td>
        <td>OPTIONS</td>
    </tr>
    <tr>
        <td>KEY</td>
        <td>VALUE</td>
        <td>OPTIONS</td>
    </tr>
    <tr>
        <td>KEY</td>
        <td>VALUE</td>
        <td>OPTIONS</td>
    </tr>
    <tr>
        <td>KEY</td>
        <td>VALUE</td>
        <td>OPTIONS</td>
    </tr>
    <tr>
        <td>KEY</td>
        <td>VALUE</td>
        <td>OPTIONS</td>
    </tr>
    <tr>
        <td>KEY</td>
        <td>VALUE</td>
        <td>OPTIONS</td>
    </tr>
    <tr>
        <td>KEY</td>
        <td>VALUE</td>
        <td>OPTIONS</td>
    </tr>
    <tr>
        <td>KEY</td>
        <td>VALUE</td>
        <td>OPTIONS</td>
    </tr>
    <tr>
        <td>KEY</td>
        <td>VALUE</td>
        <td>OPTIONS</td>
    </tr>
    <tr>
        <td>KEY</td>
        <td>VALUE</td>
        <td>OPTIONS</td>
    </tr>
    <tr>
        <td>KEY</td>
        <td>VALUE</td>
        <td>OPTIONS</td>
    </tr>
    <tr>
        <td>KEY</td>
        <td>VALUE</td>
        <td>OPTIONS</td>
    </tr>
    <tr>
        <td>KEY</td>
        <td>VALUE</td>
        <td>OPTIONS</td>
    </tr>
    <tr>
        <td>KEY</td>
        <td>VALUE</td>
        <td>OPTIONS</td>
    </tr>
    <tr>
        <td>KEY</td>
        <td>VALUE</td>
        <td>OPTIONS</td>
    </tr>
    <tr>
        <td>KEY</td>
        <td>VALUE</td>
        <td>OPTIONS</td>
    </tr>
    <tr>
        <td>KEY</td>
        <td>VALUE</td>
        <td>OPTIONS</td>
    </tr>
    <tr>
        <td>KEY</td>
        <td>VALUE</td>
        <td>OPTIONS</td>
    </tr>
    <tr>
        <td>KEY</td>
        <td>VALUE</td>
        <td>OPTIONS</td>
    </tr>
    <tr>
        <td>KEY</td>
        <td>VALUE</td>
        <td>OPTIONS</td>
    </tr>
    </tbody>

</table>