FROM store/oracle/database-enterprise:12.2.0.1
#LINK: https://www.oracle.com/br/technical-resources/articles/database-performance/oracle-db19c-com-docker.html
#LINK: https://hub.docker.com/u/huntercodexs/content/sub-75e583ed-c329-49c7-b8f6-bc103f177976
EXPOSE 1521
EXPOSE 5500
#CMD ["oracle"]
