[PROJECT-ENV-CONFIGURATION-START]

[HEADER-START]

[INFO-START]
TIP="Use true or NULL value to set the fields below"
IMPORTANT="Don't change the file layout below, only make a changes in the values."
[INFO-END]

[GLOBAL-START]
CONFIGURATION_SETUP = "{{{CONFIGURATION_SETUP}}}"
SERVICES_QUANTITY = "{{{SERVICES_QUANTITY}}}"
DOCKER_EXTRA_IMAGES = "{{{DOCKER_EXTRA_IMAGES}}}"
RESOURCES_DOCKERIZED = "{{{RESOURCES_DOCKERIZED}}}"
DOCKER_COMPOSE_VERSION = "{{{DOCKER_COMPOSE_VERSION}}}"
NETWORK_GATEWAY = "{{{NETWORK_GATEWAY}}}"

[TARGET-PROJECTS]
{{{GIT_PROJECT}}}

[DATABASE-START] #USE="HOST;PORT;USER;PASSWD;DBNAME"
DB_SETUP = "NULL"
DB_MAIN_MODEL1 = "NULL"
DB_MAIN_MODEL2 = "NULL"
[DATABASE-END]

[APP-START]
APP_SETUP = "NULL"
APP_URL_MODEL1 = "NULL"
APP_URL_MODEL2 = "NULL"
[APP-END]

[API-START]
API_SETUP = "NULL"
API_MODEL1 = "NULL"
API_MODEL2 = "NULL"
[API-END]

[GLOBAL-END]

[HEADER-END]

[SERVICE-START]
