******************************************************************************************
#SERVICE-{{{MANDATORY: SERVICE_NUMBER}}}
------------------------------------------------------------------------------------------
SERVICE_NAME = "{{{MANDATORY: SERVICE_NAME}}}"
CONTAINER_NAME = "{{{MANDATORY: SERVICE_NAME}}}"
IMAGE = "{{{MANDATORY[DEPENDS_BUILD)]: IMAGE_VALUE}}}"
PRIVILEGED = "true"
LOCALHOST_PORT = "{{{MANDATORY: HOST_PORT}}}"
INTERNAL_PORT = "{{{MANDATORY: CONTAINER_PORT}}}"
NETWORKS = "default,{{{MANDATORY: NETWORK_GATEWAY}}}"
ENVIRONMENT = "{{{OPTIONAL: NULL,true}}}"
    {{{ENV}}}
VOLUMES = "{{{OPTIONAL: NULL,true}}}"
    {{{VOLUME}}}
LINKS = "{{{OPTIONAL: NULL,true}}}"
    {{{LINK}}}
DEPENDS_ON = "{{{OPTIONAL: NULL,true}}}"
    {{{DEPEND}}}
BUILD = "{{{OPTIONAL[DEPENDS_IMAGE]: NULL,true,dockerfile,BUILDER_PATH}}}"
    CONTEXT = "./projects/{{{SERVICE_NAME}}}/"
    DOCKERFILE = "{{{SERVICE_NAME}.dockerfile}}"
WORKING_DIR = "{{{OPTIONAL: NULL,WORKING_PATH_VALUE}}}"
COMMAND = "{{{OPTIONAL: NULL,COMMAND_VALUE}}}"
ENV_FILE = "{{{OPTIONAL: NULL,env_file_path}}}"
DEPLOY = "{{{OPTIONAL: NULL,true}}}"
DEPLOY_MEMORY = "{{{OPTIONAL: NULL,MEMORY_SIZE}}}"
PROJECT_NAME = "{{{MANDATORY: SERVICE_NAME}}}"
NGINX_CONF = "{{{MANDATORY[NGINX-SERVER]: NULL,NGINX_CONF_VALUE}}}"
NGINX_SERVER_NAME = "{{{MANDATORY[NGINX-SERVER]: NULL,NGINX_SERVER_NAME_VALUE}}}"
NGINX_ROOT_PATH = "{{{MANDATORY[NGINX-SERVER]: NULL,NGINX_ROOT_PATH_VALUE}}}"
NGINX_APP_CONF = "{{{MANDATORY[NGINX-SERVER]: NULL,NGINX_APP_CONF_VALUE}}}"
NGINX_LISTEN = "{{{MANDATORY[NGINX-SERVER]: NULL,NGINX_LISTEN_VALUE}}}"
NGINX_FAST_CGI_PASS = "{{{MANDATORY[NGINX-SERVER]: NULL,NGINX_FAST_CGI_PASS_VALUE}}}"
NGINX72_CONF = "{{{OPTIONAL: NULL,true}}}"
NGINX72_RESTFUL_CONF = "{{{OPTIONAL: NULL,true}}}"
SUPERVISOR_CONF = "{{{OPTIONAL: NULL,true}}}"
